secure: "VUdKu+f/nqjMlbn00nTqqRJHMNSY9VEkeFges1lwrnKHntsQu4Y4gHV8kJETT8WaVd2IcUaBs9mCZUCODvtxeRHI/zRZThXMPpt3qG2pFjj1FXflqf9rO8p7dPEzMfkkvA84eT6FIWYgIF3W4j+IaK+laGXmNWABF7170skb3+OQBtqOoAsSimifToHfMs6FkemDz97nke4D28yHfMtGgFi/n4xVaqZxNxBhuW9W9uxP8yW8Nnp+tewhTAurf/DrGeScAgbQb5mSL1pZU1ANgy7D62vF14eIERMHJX7GOp3up1oS9F23QO/iJyD9cpZ9qF6fP+FvB8Kp3ESClsjJe+45rLCKWomRDk9izKB8AokNWxwoWYCN6ufkUiUkktn3oBvOycOSYRpPO/O9P/4rvCnmA2zFZFY4sY0Bi6wpYNiR1eV2wTMGYiByO+novtDRMhmtcoQOZzU51v/Bdlz6mV4jtyI71husIyzZGQ2aMfPYEi2trxqyEsfFe7f7GVRu67BJYOXoZv1jUaysIFjZtqyF5lChq+Z0Ec5+6tx9dYMsT6gHFPDzVg2xDOdg76rEn8Iej93RADdW8qm+7afswhRXPbsEmHzsxYxF5xY4wy6F9MfBK66V5zQ7JDTDzFbO2+Q//09yhLri4d5DJdvFOUOk6oPTuSSr3RVSWDYShdM="



language:
  - android
  - java
jdk: oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.2
  - ${ANDROID_TARGET}
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew -p common build
  - ./gradlew -p android assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew -p android connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)

test:
    post:
        - ./gradlew -p android jacocoTestReport
        - ./gradlew -p common jacocoTestReport
        - sudo pip install --user codecov && codecov:
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - android/build/outputs/lint-results_files/hololike.css
    - android/build/outputs/lint-results_files/lint-error.png
    - android/build/outputs/lint-results_files/lint-run.png
    - android/build/outputs/lint-results_files/lint-warning.png
    - android/build/outputs/lint-results.html
    - android/build/outputs/lint-results.xml
    - android/build/outputs/logs/manifest-merger-debug-report.txt
    - android/build/outputs/logs/manifest-merger-release-report.txt
    - android/build/outputs/apk/android-debug.apk
    - android/build/outputs/apk/android-debug-unaligned.apk
    - android/build/outputs/apk/android-release.apk
    - android/build/outputs/apk/android-release-unaligned.apk
    - android/build/outputs/lint-results-release-fatal_files/hololike.css
    - android/build/outputs/lint-results-release-fatal.html
    - android/build/outputs/lint-results-release-fatal.xml
    - android/build/outputs/logs/manifest-merger-debug-report.txt
    - android/build/outputs/logs/manifest-merger-release-report.txt
    - android/build/outputs/mapping/release/dump.txt
    - android/build/outputs/mapping/release/mapping.txt
    - android/build/outputs/mapping/release/seeds.txt
    - android/build/outputs/mapping/release/usage.txt
    - android/build/reports/androidTests/connected/index.html

  skip_cleanup: true
  on:
    tags: true

